Update README.md
philippejlyu/CSC302 pull request #15
Opened 2022-11-02 02:30 UTC by mulliganaceous

Note for linux users

2022-11-02 02:51 UTC, piyush-sharma requested changes
Looks great. The docker image size is definitely good information. 

I don't think we should mention the number of npm packages and "high-security vulnerabilities". 

The number of npm packages doesn't really matter since the docker image size is the more important information when it comes to size. For the vulnerabilities, `npm audit` has been broken for a very long time so those vulnerabilities don't really mean anything. Here's a great post explaining this: [npm audit broken by design](https://overreacted.io/npm-audit-broken-by-design/)

2022-11-02 23:40 UTC, philippejlyu requested changes

2022-11-02 23:40 UTC, philippejlyu commented on README.md
> +Precondition: Docker must be installed on your computer. You may need to use sudo if you are running on Linux. The Docker image will be at least 2GB in total, and 1493 npm packages are utilized. Ther
Also remove the number of packages that are added. This will likely change in the future.

2022-11-03 02:10 UTC, philippejlyu requested changes

2022-11-03 02:10 UTC, philippejlyu commented on README.md
> +Successfully built 8bdd7b654d8f
Remove 69 - 71, only confuses the reader

2022-11-06 02:06 UTC, philippejlyu approved these changes

2022-11-06 02:11 UTC, piyush-sharma approved these changes

2022-11-06 02:11 UTC, merged